common: &common
  adapter: postgresql
  username: conductor
  password: conductor
  host: localhost

development:
  <<: *common
  database: conductor_dev

test: &test
  <<: *common
  database: conductor_test

staging:
  <<: *common
  database: conductor

production:
  <<: *common
  database: conductor_dev



#create a new DB
#$ sudo -u postgres createdb conductor

#create a new user
#$ sudo -u postgres createuser conductor

#set the password
#$ sudo -u postgres psql
#postgres-# \password conductor

#set /etc/postgresql/8.4/main/pg_hba.conf access from "ident" to "md5" and restart postgres

#test the connection
#psql -Uconductor conductor

#install the new DB
#export RAILS_ENV=foo ; rake db:create

