common: &common
  adapter: postgresql
  username: conductor
  password: conductor
  host: localhost

development:
  <<: *common
  database: conductor_dev

test: &test
  <<: *common
  database: conductor_test

staging:
  <<: *common
  database: conductor

production:
  <<: *common
  database: conductor

